# Whether to make the sniffer invincible or not when high on sugar
invincibleSniffer: false
# The time the sniffer runs around before exploding (in seconds)
timeBeforeExploding: 4
# Whether to disable the sniffer's explosion or not
disableExplosion: false
# The amount of sugar needed for the explosion to have fire
minFire: 2
# Chance of the sniffer dropping its nose upon exploding (in percent)
noseDropChance: 100
# Ore sniffing duration (in seconds)
oreSniffingDuration: 60
# Ore sniffing duration for the nether (in seconds)
oreSniffingDurationNether: 10
# Range for ore detection when sniffing for ores (in blocks)
oreSniffingRange: 16
# Type of display for ore sniffing. Options: "block", "item"
# "block" will display the ore as a Block Display
# "item" will display the ore as an Item Display
oreSniffingMode: "block"
# Whether to use raw ores rather than ingots for the item display
rawMineralsForItem: false
# Enable the experimental potions (MAY NOT BE STABLE AND CAUSE CORRUPTION)
experimentalPotions: false