# Whether to make the sniffer invincible or not when high on sugar
invincibleSniffer: false
# The time the sniffer runs around before exploding (in seconds)
timeBeforeExploding: 4
# Whether to disable damage and griefing from the explosion
disableExplosion: false
# The amount of sugar needed for the explosion to have fire
minFire: 2
# Chance of the sniffer dropping its snout upon exploding (in percentage)
potionDropChance: 100
# Ore sniffing duration (in seconds)
oreSniffingDuration: 60
# Ore sniffing duration for the nether (in seconds)
oreSniffingDurationNether: 10
# Range for ore detection when sniffing for ores (in blocks)
oreSniffingRange: 16
# Type of display for ore sniffing. Options: "block", "item"
# "block" will display the ore as a Block Display
# "item" will display the ore as an Item Display
oreSniffingMode: "block"
# Whether to use raw ores rather than ingots for the item display
rawMineralsForItem: false
# Chance of the sniffers digging up slime balls in slime chunks (in percentage) (set to 0 to disable)
findSlimeChunksChance: 100
# If your server doesn't have players using different languages and you wish to disable this feature, you can do so.
disableTranslations: false

# For translations, you can use a full locale (e.g. en_US) or just the language (e.g. en)

# Translations for the Sniffing Potion item
potionTranslations:
  en: "Sniffing Potion"
  es: "Poción de esnifar"

# Translations for the Sniffing Potion's description
infoTranslations:
  en: "Instant Sniffing"
  es: "Esnifado instantáneo"
