# Whether to make the sniffer invincible or not when high on sugar
invincibleSniffer: false
# The time the sniffer runs around before exploding (in seconds)
timeBeforeExploding: 4
# Whether to disable damage and griefing from the explosion
disableExplosion: false
# The amount of sugar needed for the explosion to have fire
minFire: 2
# Chance of the sniffer dropping its snout upon exploding (in percentage)
snoutDropChance: 100
# Ore sniffing duration (in seconds)
oreSniffingDuration: 60
# Ore sniffing duration for the nether (in seconds)
oreSniffingDurationNether: 10
# Range for ore detection when sniffing for ores (in blocks)
oreSniffingRange: 16
# Type of display for ore sniffing. Options: "block", "item"
# "block" will display the ore as a Block Display
# "item" will display the ore as an Item Display
oreSniffingMode: "block"
# Whether to use raw ores rather than ingots for the item display
rawMineralsForItem: false
# Chance of the sniffers digging up slime balls in slime chunks (in percentage) (set to 0 to disable)
findSlimeChunksChance: 100
# Show lore for the sniffer snout explaining how to use
showLore: true
# If your server doesn't have players using different languages and you wish to disable this feature, you can do so.
disableTranslations: false

snoutTranslations: # Translations for the sniffer snout item
  en: "§2Sniffer Snout"
  es: "§2Nariz de Sniffer"

loreTranslations: # Translations for the sniffer snout lore
  en: "§6Click to §e§lSNIFF"
  es: "§6Haz click para §e§lSNIFFEAR"