# Exploding Sniffers Feature
high_on_sugar:
  # Enable or disable this feature
  enabled: true
  # When true, the sniffer will be invincible when high on sugar
  invincible_sniffer: false
  # The time the sniffer runs around before exploding (in seconds)
  time_before_exploding: 4.0
  # When true, damage and griefing from the explosion will be disabled
  pacific_explosion: false
  # The amount of sugar needed for the explosion to have fire (set to 0 to disable)
  min_fire: 2
  # Initial speed of the sniffer
  initial_speed: 10.0
  # Chance of the sniffer dropping the Potion of Sniffing upon exploding (in percentage)
  potion_drop_chance: 100.0

# Potion of Sniffing Feature
potion_of_sniffing:
  # Enable or disable this feature
  enabled: true
  # The world(s) where the potion is enabled with its duration (in seconds) and radius (in blocks)
  enabled_worlds:
    world:
      duration: 60.0
      radius: 16
    world_nether:
      duration: 10.0
      radius: 16
  # Type of display for ore sniffing. Options: "block", "ingot", "raw"
  # "block" will display the ore as a Block Display
  # "ingot" will display the ore as an Item Display showing the ingot versions of the ore
  # "raw" will display the ore as an Item Display showing the raw ore
  ore_sniffing_mode: "block"

# Slime Chunk Finding Feature
slime_sniffing:
  # Enable or disable this feature
  enabled: true
  # Chance of the sniffers digging up slime balls in slime chunks (in percentage)
  dig_up_slime_chance: 40.0

# Translation Feature
translations:
  # If your server doesn't have players using different languages, and you wish to disable this feature, you can do so.
  enabled: true
  # For translations, you can use a full locale (e.g. en_US) or just the language (e.g. en)
  # Translations for the normal Sniffing Potion item
  potion_translations:
    en: "Potion of Sniffing"
    es: "Poci칩n de esnifado"
  # Translations for the splash Sniffing Potion item
  splash_translations:
    en: "Splash Potion of Sniffing"
    es: "Poci칩n arrojadiza de esnifado"
  # Translations for the lingering Sniffing Potion item
  lingering_translations:
    en: "Lingering Potion of Sniffing"
    es: "Poci칩n persistente de esnifado"
  # Translations for the Sniffing Potion's description
  info_translations:
    en: "Instant Sniffing"
    es: "Esnifado instant치neo"
