name: SnifferExploited
version: '${project.version}'
main: code.blurone.snifferexploited.SnifferExploited
api-version: '1.20'
author: 'BlurOne!'
website: 'https://github.com/BlurOne-GIT/Sniffer-Exploited'
commands:
  sniff:
    description: 'Sniff for ores'
    usage: '/sniff <duration> <radius>'
    permission: 'snifferexploited.sniff'
  potionofsniffing:
    description: 'Get the Potion of Sniffing'
    usage: '/potionofsniffing [potion|splash|lingering]'
    permission: 'snifferexploited.potionofsniffing'
